var Pixastic=function(){function h(a,c,d){a.addEventListener?a.addEventListener(c,d,!1):a.attachEvent&&a.attachEvent("on"+c,d)}function e(a){var c=!1,d=function(){c||(c=!0,a())};document.write('<script defer src="//:" id="__onload_ie_pixastic__"><\/script>');var b=document.getElementById("__onload_ie_pixastic__");b.onreadystatechange=function(){b.readyState=="complete"&&(b.parentNode.removeChild(b),d())};document.addEventListener&&document.addEventListener("DOMContentLoaded",d,!1);h(window,"load",
d)}function g(){for(var a=k("pixastic",null,"img"),c=k("pixastic",null,"canvas"),d=a.concat(c),b=0;b<d.length;b++)(function(){for(var a=d[b],c=[],e=a.className.split(" "),g=0;g<e.length;g++){var h=e[g];h.substring(0,9)=="pixastic-"&&(h=h.substring(9),h!=""&&c.push(h))}if(c.length)if(a.tagName.toLowerCase()=="img")if(e=new Image,e.src=a.src,e.complete)for(e=0;e<c.length;e++)(g=Pixastic.applyAction(a,a,c[e],null))&&(a=g);else e.onload=function(){for(var b=0;b<c.length;b++){var d=Pixastic.applyAction(a,
a,c[b],null);d&&(a=d)}};else setTimeout(function(){for(var b=0;b<c.length;b++){var d=Pixastic.applyAction(a,a,c[b],null);d&&(a=d)}},1)})()}function k(a,c,d){var b=[];c==null&&(c=document);d==null&&(d="*");c=c.getElementsByTagName(d);d=c.length;a=RegExp("(^|\\s)"+a+"(\\s|$)");for(i=0,j=0;i<d;i++)a.test(c[i].className)&&(b[j]=c[i],j++);return b}function p(a,c){if(Pixastic.debug)try{switch(c){case "warn":console.warn("Pixastic:",a);break;case "error":console.error("Pixastic:",a);break;default:console.log("Pixastic:",
a)}}catch(d){}}typeof pixastic_parseonload!="undefined"&&pixastic_parseonload&&e(g);var o=function(){var a=document.createElement("canvas"),c=!1;try{c=!!(typeof a.getContext=="function"&&a.getContext("2d"))}catch(d){}return function(){return c}}(),n=function(){var a=document.createElement("canvas"),c=!1,d;try{if(typeof a.getContext=="function"&&(d=a.getContext("2d")))c=typeof d.getImageData=="function"}catch(b){}return function(){return c}}(),l=function(){var a=!1,c=document.createElement("canvas");
if(o()&&n()){c.width=c.height=1;c=c.getContext("2d");c.fillStyle="rgb(255,0,0)";c.fillRect(0,0,1,1);var d=document.createElement("canvas");d.width=d.height=1;var b=d.getContext("2d");b.fillStyle="rgb(0,0,255)";b.fillRect(0,0,1,1);c.globalAlpha=0.5;c.drawImage(d,0,0);a=c.getImageData(0,0,1,1).data[2]!=255}return function(){return a}}();return{parseOnLoad:!1,debug:!1,applyAction:function(a,c,d,b){var b=b||{},e=a.tagName.toLowerCase()=="canvas";if(e&&Pixastic.Client.isIE())return Pixastic.debug&&p("Tried to process a canvas element but browser is IE."),
!1;var f,g,h=!1;Pixastic.Client.hasCanvas()&&(h=!!b.resultCanvas,f=b.resultCanvas||document.createElement("canvas"),g=f.getContext("2d"));var k=a.offsetWidth,l=a.offsetHeight;if(e)k=a.width,l=a.height;if(k==0||l==0)if(a.parentNode==null){var m=a.style.position,n=a.style.left;a.style.position="absolute";a.style.left="-9999px";document.body.appendChild(a);k=a.offsetWidth;l=a.offsetHeight;document.body.removeChild(a);a.style.position=m;a.style.left=n}else{Pixastic.debug&&p("Image has 0 width and/or height.");
return}if(d.indexOf("(")>-1&&(m=d,d=m.substr(0,m.indexOf("(")),m=m.match(/\((.*?)\)/),m[1])){m=m[1].split(";");for(n=0;n<m.length;n++)if(thisArg=m[n].split("="),thisArg.length==2)if(thisArg[0]=="rect"){var o=thisArg[1].split(",");b[thisArg[0]]={left:parseInt(o[0],10)||0,top:parseInt(o[1],10)||0,width:parseInt(o[2],10)||0,height:parseInt(o[3],10)||0}}else b[thisArg[0]]=thisArg[1]}b.rect?(b.rect.left=Math.round(b.rect.left),b.rect.top=Math.round(b.rect.top),b.rect.width=Math.round(b.rect.width),b.rect.height=
Math.round(b.rect.height)):b.rect={left:0,top:0,width:k,height:l};m=!1;Pixastic.Actions[d]&&typeof Pixastic.Actions[d].process=="function"&&(m=!0);if(!m)return Pixastic.debug&&p('Invalid action "'+d+'". Maybe file not included?'),!1;if(!Pixastic.Actions[d].checkSupport())return Pixastic.debug&&p('Action "'+d+'" not supported by this browser.'),!1;if(Pixastic.Client.hasCanvas()){if(f!==a)f.width=k,f.height=l;if(!h)f.style.width=k+"px",f.style.height=l+"px";g.drawImage(c,0,0,k,l);a.__pixastic_org_image?
(f.__pixastic_org_image=a.__pixastic_org_image,f.__pixastic_org_width=a.__pixastic_org_width,f.__pixastic_org_height=a.__pixastic_org_height):(f.__pixastic_org_image=a,f.__pixastic_org_width=k,f.__pixastic_org_height=l)}else if(Pixastic.Client.isIE()&&typeof a.__pixastic_org_style=="undefined")a.__pixastic_org_style=a.style.cssText;c={image:a,canvas:f,width:k,height:l,useData:!0,options:b};if(!Pixastic.Actions[d].process(c))return!1;if(Pixastic.Client.hasCanvas()){c.useData&&Pixastic.Client.hasCanvasImageData()&&
(f.getContext("2d").putImageData(c.canvasData,b.rect.left,b.rect.top),f.getContext("2d").fillRect(0,0,0,0));if(!b.leaveDOM){f.title=a.title;f.imgsrc=a.imgsrc;if(!e)f.alt=a.alt;if(!e)f.imgsrc=a.src;f.className=a.className;f.style.cssText=a.style.cssText;f.name=a.name;f.tabIndex=a.tabIndex;f.id=a.id;a.parentNode&&a.parentNode.replaceChild&&a.parentNode.replaceChild(f,a)}return b.resultCanvas=f}return a},prepareData:function(a,c){var d=a.canvas.getContext("2d"),b=a.options.rect,d=d.getImageData(b.left,
b.top,b.width,b.height),b=d.data;if(!c)a.canvasData=d;return b},process:function(a,c,d,b){if(a.tagName.toLowerCase()=="img"){var e=new Image;e.src=a.src;if(e.complete){var f=Pixastic.applyAction(a,e,c,d);b&&b(f);return f}else e.onload=function(){var f=Pixastic.applyAction(a,e,c,d);b&&b(f)}}if(a.tagName.toLowerCase()=="canvas")return f=Pixastic.applyAction(a,a,c,d),b&&b(f),f},revert:function(a){if(Pixastic.Client.hasCanvas()){if(a.tagName.toLowerCase()=="canvas"&&a.__pixastic_org_image)return a.width=
a.__pixastic_org_width,a.height=a.__pixastic_org_height,a.getContext("2d").drawImage(a.__pixastic_org_image,0,0),a.parentNode&&a.parentNode.replaceChild&&a.parentNode.replaceChild(a.__pixastic_org_image,a),a}else if(Pixastic.Client.isIE()&&typeof a.__pixastic_org_style!="undefined")a.style.cssText=a.__pixastic_org_style},Client:{hasCanvas:o,hasCanvasImageData:n,hasGlobalAlpha:l,isIE:function(){return!!document.all&&!!window.attachEvent&&!window.opera}},Actions:{}}}();
Pixastic.Actions.fliph={process:function(h){if(Pixastic.Client.hasCanvas()){var e=h.options.rect,g=document.createElement("canvas");g.width=e.width;g.height=e.height;g.getContext("2d").drawImage(h.image,0,0);var k=h.canvas.getContext("2d");k.clearRect(e.left,e.top,e.width,e.height);k.scale(-1,1);k.drawImage(g,-e.left-e.width,e.top,e.width,e.height);h.useData=!1;return!0}else if(Pixastic.Client.isIE())return h.image.style.filter+=" fliph",!0},checkSupport:function(){return Pixastic.Client.hasCanvas()||
Pixastic.Client.isIE()}};
Pixastic.Actions.flipv={process:function(h){if(Pixastic.Client.hasCanvas()){var e=h.options.rect,g=document.createElement("canvas");g.width=e.width;g.height=e.height;g.getContext("2d").drawImage(h.image,0,0);var k=h.canvas.getContext("2d");k.clearRect(e.left,e.top,e.width,e.height);k.scale(1,-1);k.drawImage(g,e.left,-e.top-e.height,e.width,e.height);h.useData=!1;return!0}else if(Pixastic.Client.isIE())return h.image.style.filter+=" flipv",!0},checkSupport:function(){return Pixastic.Client.hasCanvas()||Pixastic.Client.isIE()}};
Pixastic.Actions.sepia={process:function(h){var e=parseInt(h.options.mode,10)||0;e<0&&(e=0);e>1&&(e=1);if(Pixastic.Client.hasCanvasImageData()){var g=Pixastic.prepareData(h),k=h.options.rect,h=k.width,p=h*4,k=k.height;do{var o=(k-1)*p,n=h;do{var l=o+(n-1)*4;if(e){var a=g[l]*0.299+g[l+1]*0.587+g[l+2]*0.114,c=a+39,d=a+14;a-=36}else var a=g[l],b=g[l+1],q=g[l+2],c=a*0.393+b*0.769+q*0.189,d=a*0.349+b*0.686+q*0.168,a=a*0.272+b*0.534+q*0.131;c<0&&(c=0);c>255&&(c=255);d<0&&(d=0);d>255&&(d=255);a<0&&(a=0);
a>255&&(a=255);g[l]=c;g[l+1]=d;g[l+2]=a}while(--n)}while(--k);return!0}},checkSupport:function(){return Pixastic.Client.hasCanvasImageData()}};
