<?php
/* 
	// ======================================== \
	// Package: MultiHoster
	// Version: 6.0.0
	// Copyright (c) 2007-2013 Mihalism Technologies
	// Copyright (c) 2011-2013 MultiHosterScript.com
	// License: http://www.gnu.org/licenses/gpl.txt GNU Public License
	// LTE: 1253515339 - Monday, September 21, 2009, 02:42:19 AM EDT -0400
	// ======================================== /
     
     This file contains some language settings that are a part of MultiHoster but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by MultiHoster; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Image download page title
		002 -- Error to be displayed when no filename is given to download
		003 -- Error to be displayed if the given file to download does not exist

*/
    
	$mmhclass->lang['001'] = "%s » Image Download";
	$mmhclass->lang['002'] = "No filename has been supplied.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['003'] = "The image file <b>%s</b> does not exist. <br />
Please ensure the filename is spelled correctly.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";


?>