<?php
/* 
     // ======================================== \
     // Package: Mihalism Multi Host
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: 1248917687 - Wednesday, July 29, 2009, 08:34:47 PM CDT -0500
     // ======================================== /
     
     This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Page title for public gallery page
		002 -- Message to be displayed when public gallery viewing is disabled
		003 -- Message to be displayed when there are no Guest uploaded images

*/
    
	$mmhclass->lang['001'] = "%s » Public Gallery";
	$mmhclass->lang['002'] = "Viewing of this gallery has been set to private.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['003'] = "Gallery is empty.";


?>