<?php
/* 
     // ======================================== \
     // Package: Mihalism Multi Host
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: 1251384545 - Thursday, August 27, 2009, 10:49:05 AM EDT -0400
     // ======================================== /
     
     This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Default page title for home page
		002 -- Page title for URL upload page
		003 -- Allowed file extensions list grammatical conjuncture
		004 -- Message to be displayed when uploading is disabled
		005 -- Page title for when uploading is disabled
		006 -- Error to be displayed when no random image is found
		007 -- Message to be displayed when uploading is disabled for Guests

*/
    
	$mmhclass->lang['001'] = "Welcome to %s, a free image upload solution. Simply browse, select, and upload!";
	$mmhclass->lang['002'] = "URL Upload - %s";
	$mmhclass->lang['003'] = "and";
	$mmhclass->lang['004'] = "Uploading is currently disabled.";
	$mmhclass->lang['005'] = "Uploading Disabled";
	$mmhclass->lang['006'] = "No publicly uploaded images were found.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['007'] = "Sorry, but uploading is restricted to registered users. <br />
Please log in by clicking above to begin uploading.";


?>
