<?php
/* 
    // ======================================== \
	// Package: MultiHoster
	// Version: 6.0.0
	// Copyright (c) 2007-2013 Mihalism Technologies
	// Copyright (c) 2011-2013 MultiHosterScript.com
	// License: http://www.gnu.org/licenses/gpl.txt GNU Public License
	// LTE: 1253515339 - Monday, September 21, 2009, 02:42:19 AM EDT -0400
	// ======================================== /
     
     This file contains some language settings that are a part of MultiHoster but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by MultiHoster; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Default page title for home page
		002 -- Page title for URL upload page
		003 -- Allowed file extensions list grammatical conjuncture
		004 -- Message to be displayed when uploading is disabled
		005 -- Page title for when uploading is disabled
		006 -- Error to be displayed when no random image is found
		007 -- Message to be displayed when uploading is disabled for Guests

*/
    
	$mmhclass->lang['001'] = "Welcome to %s, a free image upload solution.";
	$mmhclass->lang['002'] = "URL Upload - %s";
	$mmhclass->lang['003'] = "and";
	$mmhclass->lang['004'] = "Uploading is currently disabled.";
	$mmhclass->lang['005'] = "Uploading Disabled";
	$mmhclass->lang['006'] = "No publicly uploaded images were found.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['007'] = "Sorry, but uploading is restricted to registered users only. <br />
Please log in to begin uploading.";


?>
