<?php
/* 
     // ======================================== \
     // Package: Mihalism Multi Host
     // Version: 5.0.4
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // ModCP Languagefile, based uppon AdminCP language file
     // by TheKPM
     // ======================================== /
     
     This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
     
     Language file index:
		002 -- Error to be displayed if an user is not an moderator or administrator
		009 -- Error to be displayed if an invalid number of input paramters (GET/POST) are supplied
		362 -- Error to be displayed if all form fields have not been filled in completely
		383 -- Catchall error for nonexistent pages
		463 -- Message to be displayed if a gallery is empty
		530 -- Error to be displayed if no filename is supplied
		843 -- Error to be displayed if a file does not exist
		460 -- Error to be displayed if a file fails to delete
		687 -- Error to be displayed if a thumbnail fails to delete
		565 -- Message to be displayed when an image has been deleted
		781 -- Notice to be used for standard uploads in file logs
		441 -- Notice to be used for URL uploads in file logs
		317 -- Message to be displayed when ban filter has been updated
		375 -- Error to be displayed if an invalid reCAPTCHA code is given
		481 -- Notice to be used for private galleries in user list page
		646 -- Notice to be used for public galleries in user list page
		278 -- Error to be displayed if a user does not exist
		112 -- Error to be displayed if an invalid email address is given
		337 -- Error to be displayed if an invalid password is given
		772 -- Error to be displayed if a normal admin tries to change the root admin's settings
		330 -- Message to be displayed when user settings have been saved
		598 -- Error to be displayed if a search returns no results
		413 -- Message to be displayed when images have been moved
		746 -- Error to be displayed if an album name is already in use
		412 -- Message to be displayed when a new album has been created
		338 -- Error to be displayed if an album cannot be renamed
		101 -- Message to be displayed when an album has been renamed
		442 -- Error to be displayed if an album cannot be deleted
		738 -- Message to be displayed when an album has been deleted
		906 -- Error to be displayed if album does not exist when moving images
		540 -- Error to be displayed if .htaccess file fails to open
*/
    	
	$mmhclass->lang['002'] = "You must be logged in as a moderator site administrator to view this page.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['009'] = "An invalid number of input parameters (<a href=\"http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods\" target=\"_new\">GET / POST</a>) have been supplied.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['362'] = "The form on the previous page has not been filled in completely. <br />
One or more fields have been left blank. Please try again.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['383'] = "You have reached this page in error. Please use your back button to return to the previous page.";
	$mmhclass->lang['463'] = "Gallery is empty.";
	$mmhclass->lang['530'] = "No filename has been supplied.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['843'] = "The image file <b>%s</b> does not exist! <br />
Please ensure the filename is spelled correctly.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['460'] = "The image file <b>%s</b> is unable to be deleted.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['687'] = "The thumbnail of the image file <b>%s</b> could not be deleted.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['565'] = "Images have been successfully deleted.<br />
<br />
<a href=\"index.php?rurl=%s\">Return to Previous Page</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['781'] = "Normal";
	$mmhclass->lang['441'] = "URL";
	$mmhclass->lang['317'] = "Ban filter has been successfully updated. <br />
<br />
<a href=\"modcp.php?act=ban_control\">Return to Previous Page</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['375'] = "The security code entered did not match the one displayed. <br />
A new code has been generated. Please try again.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['481'] = "Private";
	$mmhclass->lang['646'] = "Public";
	$mmhclass->lang['278'] = "User does not exist. Please try again. <br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['112'] = "The email address <b>%s</b> appears to be in an invalid format.<br />
A valid address would look like: <b>username@example.com</b>.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['337'] = "The password entered is not valid based on the specified requirements. <br />
It is either too long or too short. Please try again.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['772'] = "Protected User. Root Access Required.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['330'] = "User settings have been successfully saved. <br />
<br />
<a href=\"modcp.php?act=user_list\">Return to User Management</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['598'] = "No results found.";
	$mmhclass->lang['413'] = "Images have been successfully moved.<br />
<br />
<a href=\"index.php?rurl=%s\">Return to Previous Page</a><br />
<a href=\"modcp.php?gal=%s&cat=%s\">Go to New Album</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['746'] = "The album name <b>%s</b> is already in use. Please try again.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['412'] = "The album <b>%s</b> has been successfully created.<br />
<br />
<a href=\"index.php?rurl=%s\">Return to Previous Page</a><br />
<a href=\"modcp.php?gal=%s&cat=%s\">Go to New Album</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['338'] = "The requested album is unable to be renamed.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['101'] = "The album <b>%s</b> has been successfully renamed to <b>%s</b>.<br />
<br />
<a href=\"index.php?rurl=%s\">Return to Previous Page</a><br />
<a href=\"modcp.php?gal=%s&cat=%s\">Go to Renamed Album</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['442'] = "The requested album is unable to be deleted.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['738'] = "The requested album has been successfully deleted.<br />
<br />
<a href=\"modcp.php?gal=%s\">Return to User Gallery</a><br />
<a href=\"modcp.php\">ModCP Index</a>";
	$mmhclass->lang['906'] = "Destination album does not exist.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";
	$mmhclass->lang['540'] = "Failed to open .htaccess file for writing. Please try again.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">Return to Previous Page</a>";


?>