<?php
/* 
	 // ======================================== \
	 // Package: Mihalism Multi Host
	 // Version: 5.0.0
	 // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
	 // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
	 // LTE: 1248458686 - Friday, July 24, 2009, 02:04:46 PM EDT -0400
	 // ======================================== /
	 
	 This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
	 be placed into template files. In each setting, %s represents a place holder for a value that will 
	 be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
	 
	 Language file index:
		 001 -- Page title for tools page
*/
	
	$mmhclass->lang['001'] = "%s &raquo; Tools";
	
?>